version: '3.7'

services:
  redis: 
    build:
      context: .
      dockerfile: docker/infra/redis.Dockerfile
    networks:
      - "wrapperizer"
  rabbitmq: 
    build: 
      context: .
      dockerfile: docker/infra/rabbitmq/rabbit.Dockerfile
    networks:
      - "wrapperizer"
    ports: 
      - 15675:15672
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 10
      test: 
        - "CMD"
        - "rabbitmqctl"
        - "status"
  sqlserver:
    build:
      context: .
      dockerfile: docker/infra/sql.Dockerfile
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@assw0rd
    ports:
      - 1444:1433
    networks:
      - "wrapperizer"
  mongo:
    build: 
      context: .
      dockerfile: docker/infra/mongo.Dockerfile
    ports:
      - 27027:27017
    networks:
      - "wrapperizer"
  api: 
    build:
      context: .
      dockerfile: docker/services/api.Dockerfile
    networks:
      - "wrapperizer"
    ports:
      - 3080:80
    environment:
      ASPNETCORE_URLS: "http://*:80"
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - mongo
      - redis
      - rabbitmq
      - sqlserver
  relay:
    build:
      context: .
      dockerfile: docker/services/relay.Dockerfile
    networks:
      - "wrapperizer"
    environment:
      ASPNETCORE_URLS: "http://*:80"
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - api
      - rabbitmq
      - sqlserver
  notification:
    build:
      context: .
      dockerfile: docker/services/notification.Dockerfile
    networks:
      - "wrapperizer"
    environment:
      ASPNETCORE_URLS: "http://*:80"
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - rabbitmq
  health:
    build:
      context: .
      dockerfile: docker/services/health.Dockerfile
    networks:
      - "wrapperizer"
    ports:
      - 3081:80
    environment:
      ASPNETCORE_URLS: "http://*:80"
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - api
      - notification
      - relay
      - mongo
      - redis
      - rabbitmq
      - sqlserver
        
networks:
  wrapperizer:
