version: '3.7'

services:
  api: 
    build:
      context: .
      dockerfile: docker/services/api.Dockerfile
    networks:
      - "wrapperizer"
    ports:
      - 3080:80
    environment:
      ASPNETCORE_URLS: "http://api:80"
      ASPNETCORE_ENVIRONMENT: "Docker"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
    depends_on:
      - consul
      - mongo
      - redis
      - rabbitmq
      - sqlserver
  relay:
    build:
      context: .
      dockerfile: docker/services/relay.Dockerfile
    networks:
      - "wrapperizer"
    restart: unless-stopped
    environment:
      DOTNET_URLS: "http://*:80"
      DOTNET_ENVIRONMENT: "Docker"
    depends_on:
      - api
      - rabbitmq
      - sqlserver
  notification:
    build:
      context: .
      dockerfile: docker/services/notification.Dockerfile
    networks:
      - "wrapperizer"
    restart: unless-stopped
    environment:
      DOTNET_URLS: "http://*:80"
      DOTNET_ENVIRONMENT: "Docker"
    depends_on:
      - rabbitmq
  health:
    build:
      context: .
      dockerfile: docker/services/health.Dockerfile
    networks:
      - "wrapperizer"
    restart: unless-stopped
    ports:
      - 3081:80
    environment:
      ASPNETCORE_URLS: "http://*:80"
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - api
      - notification
      - relay

networks:
  wrapperizer:
